version: '3.9'

services:
  backend:
    build: .
    container_name: travelPhoto-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      FLYWAY_BASELINE:        "false"
    ports:
      - "${SERVER_PORT:-8068}:${SERVER_PORT:-8068}"
    volumes:
      - ${STORAGE_ROOT_PATH:-/data/photo-storage}:/data/photo-storage
    networks:
      - shared-network
networks:
  shared-network:
    name: ${EXTERNAL_NETWORK_NAME:-shared-network}
    external: true